---
baseURL: "/"
languageCode: "en-us"
title: "Fluxnova documentation"
theme: "fluxnova"

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: "https://docs.fluxnova.finos.org"
  version: "1.0"
  forum:
    url: "https://github.com/finos/fluxnova-modeler/discussions"
    name: "Fluxnova Forum"
  section:
    id: "manual"
    version: "develop"
    versionAlias: "1.0"
    versions:
      - "latest"
      - "1.0"
      - "develop"
  # base URLs with optional version number in path using placeholder %s
  openApiBaseURL: "https://docs.fluxnova.finos.org/rest/fluxnova-bpm-platform/%s"
  javadocsBaseURL: "https://docs.fluxnova.finos.org/javadocs/%s"
  
  github:
    # repositoryName: "finos/fluxnova-docs-manual"
    branch: "main"    

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
...
